version: "3"

services:
    web:
      image: webdevops/php-apache:alpine-php7
      ports:
        - "4500:80"
      volumes:
        - ./src:/app

    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./my.cnf:/etc/conf.d/my.cnf
      environment:
        MYSQL_ROOT_PASSWORD: qwertyuiop
        # volumes default mysql /var/lib/mysql
      #volumes:
      #  - my-datavolume:/var/lib/mysql
      #ports:
      #  - "3306:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_ROOT_PASSWORD:  qwertyuiop
      ports:
      - "8088:80"
